### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [sarteleb/tc359-project2#1]
This isn't completely valid HTML unfortunately. Try making sure your HTML files don't return any errors (warnings are OK) when uploaded to [the W3C Validator](http://validator.w3.org/), then let me know when the repo is updated.

**Comment by sarteleb** [comment]
Fixed......We're supposed to be writing HTML 5 right?

**Comment by chrisvfritz** [comment]
Yep, HTML5. Though it looks like I'm still seeing errors when running [your Heroku app](https://tc359-project1-sarteleb.herokuapp.com/) through the validator. :confused:

**Comment by sarteleb** [comment]
I'm guessing this is because i'm only part of the way through project 4 which i believe is not due this week.  Project 2 and 3's html files are all checking through properly.

**Comment by chrisvfritz** [comment]
The problem is I have scripts I use locally to run some checks on GitHub code and the rendered Heroku output and it takes quite a bit more time to review projects if I have to go through everything manually. Can you update the unapproved projects with a link to a Heroku app that meets their requirements and does still pass the validator?

**Comment by sarteleb** [comment]
Ok i'll figure something out.  What do we do about tomorrow?

On Sun, Feb 1, 2015 at 6:01 PM, Chris Fritz notifications@github.com
wrote:

> The problem is I have scripts I use locally to run some checks on GitHub
> code and the rendered Heroku output and it takes quite a bit more time to
> review projects if I have to go through everything manually. Can you update
> the unapproved projects with a link to a Heroku app that meets their
> requirements and does still pass the validator?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sarteleb/tc359-project2/issues/1#issuecomment-72389860
> .

## 

Thanks,
Brandon Sartele

**Comment by sarteleb** [comment]
Reverted it back to my project 3 heroku app.  Checked out fine on my end.

**Comment by chrisvfritz** [comment]
:+1: Looks good. Thanks for updating!
